version: '2'
services:
  kafka-offset-monitor:
    image: daocloud.io/ecar/kafka-offset-monitor:master-f3ed0a3
    hostname: kafka-offset-monitor
    networks:
      evm_prd:
        aliases:
        - kafka-offset-monitor
    ports:
    - 8080:8080/tcp
networks:
  evm_prd:
    external: true
